"""Render a Report as Markdown or JSON."""

import json
from typing import Any, Dict

from .findings import CATEGORY_MEANING, CATEGORY_TITLES, Category, Report

HEADER = """# Satoshi PGP Security Audit

**Target key** `{fingerprint}`
**Key ID** `{key_id}` | **Created** {created} | **Algorithm** {algo}

> This report separates what is true of the *software* from what is true of the
> *key*. Those are different claims. A defect in GnuPG 1.4.7 does not become a
> defect in a key generated by it unless the exploit's prerequisites are met by
> material that actually exists in public.

"""

SUMMARY_TABLE = """## Summary

| Category | Meaning | Findings |
|---|---|---:|
| **A** | Definitely apply to the historical software | {A} |
| **B** | Theoretically apply, require unavailable state/observations | {B} |
| **C** | Anomalies visible in the public key/signatures | {C} |
| **D** | Reproduced successfully with synthetic keys | {D} |
| **E** | Conclusively ruled out | {E} |

"""


def to_markdown(report: Report) -> str:
    t = report.target
    out = [HEADER.format(
        fingerprint=t.get("fingerprint", "?"), key_id=t.get("key_id", "?"),
        created=t.get("created_utc", "?"), algo=t.get("algorithm", "?"))]

    bl = t.get("bottom_line")
    if bl:
        out.append("## Bottom line\n\n%s\n\n" % bl)

    counts = {c.value: len(report.by_category(c)) for c in Category}
    out.append(SUMMARY_TABLE.format(**counts))

    for cat in Category:
        findings = report.by_category(cat)
        out.append("---\n\n## Category %s - %s\n\n" % (cat.value, CATEGORY_TITLES[cat]))
        out.append("_%s_\n\n" % CATEGORY_MEANING[cat])
        if not findings:
            out.append("_No findings in this category._\n\n")
            continue
        for f in findings:
            out.append("### %s\n\n%s\n\n" % (f.title, f.summary))
            if f.requires:
                out.append("**Requires:** %s\n\n" % f.requires)
            if f.evidence:
                out.append("**Evidence:**\n\n")
                for e in f.evidence:
                    out.append("- %s\n" % e)
                out.append("\n")
            if f.reproduce_with:
                out.append("**Reproduce:**\n\n```bash\n%s\n```\n\n" % f.reproduce_with)
            if f.references:
                out.append("**References:** %s\n\n" % ", ".join(f.references))

    if report.provenance:
        out.append("---\n\n## Provenance\n\n")
        out.append("```json\n%s\n```\n\n" % json.dumps(report.provenance, indent=2))
    if report.environment:
        out.append("## Environment\n\n")
        for k, v in report.environment.items():
            out.append("- **%s**: %s\n" % (k, v))
        out.append("\n")
    return "".join(out)


def to_json(report: Report) -> str:
    return json.dumps(report.to_dict(), indent=2, default=str)
