"""Bitcoin/ECDSA scope boundary, and tools to test claimed Satoshi-signed messages.

WHY THIS MODULE EXISTS
----------------------
The obvious follow-up question to "was Satoshi's PGP key generated by weak software?"
is "what about the wallet he signed a message with?". The answer has to be stated
precisely, because the two artefacts share no cryptography whatsoever:

                    PGP key 0x5EC948A1        Bitcoin keys
    algorithm       DSA-1024 (+Elgamal-2048)  ECDSA over secp256k1
    generator       GnuPG 1.4.x               OpenSSL (bundled with Bitcoin 0.1)
    RNG             GnuPG rndw32/rndlinux     OpenSSL RAND_* (RC4/SHA1-MD)
                    -> 600-byte RIPEMD-160 pool

Consequently NO finding about GnuPG's RNG - CVE-2016-6313 included - transfers to the
Bitcoin keys. They are separate systems that happen to share an owner. This module
enforces that boundary explicitly rather than leaving it implicit, and the report
layer refuses to place a GnuPG finding in a Bitcoin conclusion.

WHAT PUBLIC ECDSA MATERIAL ACTUALLY EXISTS
------------------------------------------
An unspent output publishes a public key or its hash, never a signature. Satoshi's
holdings are overwhelmingly unspent coinbase rewards, so they contribute ZERO ECDSA
signatures. Signatures only exist where coins actually moved - the canonical example
being the block-9 coinbase spend to Hal Finney on 2009-01-12.

This module does not ship any assertion about which addresses are Satoshi's, because
that attribution is contested and not cryptographically decidable. It provides the
machinery to test material the operator supplies, and reports what that material
does or does not establish.
"""

import hashlib
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------- secp256k1
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
A = 0
B = 7
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
G = (GX, GY)

DOMAIN_SEPARATION = {
    "pgp_key_5EC948A1": {
        "signature_algorithm": "DSA (FIPS 186) over a 1024-bit prime field",
        "generator_software": "GnuPG 1.4.x (claimed 1.4.7 MingW32, unauthenticated)",
        "rng": "GnuPG internal 600-byte RIPEMD-160 entropy pool (cipher/random.c)",
        "cve_2016_6313_applicable": True,
    },
    "bitcoin_keys": {
        "signature_algorithm": "ECDSA over secp256k1",
        "generator_software": "OpenSSL, as bundled with Bitcoin 0.1 (2009)",
        "rng": "OpenSSL RAND_bytes - a wholly separate implementation",
        "cve_2016_6313_applicable": False,
        "reason": "CVE-2016-6313 is a defect in GnuPG's cipher/random.c mix_pool(). "
                  "That code is never executed by Bitcoin, which links OpenSSL. "
                  "No GnuPG RNG finding can propagate to a Bitcoin key.",
    },
}


def _inv(a: int, m: int = P) -> int:
    return pow(a, -1, m)


def point_add(p1: Optional[Tuple[int, int]],
              p2: Optional[Tuple[int, int]]) -> Optional[Tuple[int, int]]:
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    x1, y1 = p1
    x2, y2 = p2
    if x1 == x2 and (y1 + y2) % P == 0:
        return None
    if p1 == p2:
        lam = (3 * x1 * x1 + A) * _inv(2 * y1) % P
    else:
        lam = (y2 - y1) * _inv((x2 - x1) % P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def point_mul(k: int, point: Optional[Tuple[int, int]] = G) -> Optional[Tuple[int, int]]:
    k %= N
    result = None
    addend = point
    while k:
        if k & 1:
            result = point_add(result, addend)
        addend = point_add(addend, addend)
        k >>= 1
    return result


def _decompress(x: int, odd: bool) -> Optional[Tuple[int, int]]:
    alpha = (pow(x, 3, P) + B) % P
    beta = pow(alpha, (P + 1) // 4, P)
    if pow(beta, 2, P) != alpha:
        return None
    y = beta if (beta % 2 == 1) == odd else P - beta
    return (x, y)


# ---------------------------------------------------------------- encodings
def sha256(b: bytes) -> bytes:
    return hashlib.sha256(b).digest()


def hash256(b: bytes) -> bytes:
    return sha256(sha256(b))


def hash160(b: bytes) -> bytes:
    h = hashlib.new("ripemd160")
    h.update(sha256(b))
    return h.digest()


_B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58check(payload: bytes) -> str:
    raw = payload + hash256(payload)[:4]
    num = int.from_bytes(raw, "big")
    out = ""
    while num:
        num, rem = divmod(num, 58)
        out = _B58[rem] + out
    return "1" * (len(raw) - len(raw.lstrip(b"\x00"))) + out


def pubkey_to_address(pub: Tuple[int, int], compressed: bool, version: int = 0) -> str:
    x, y = pub
    if compressed:
        ser = bytes([2 + (y & 1)]) + x.to_bytes(32, "big")
    else:
        ser = b"\x04" + x.to_bytes(32, "big") + y.to_bytes(32, "big")
    return b58check(bytes([version]) + hash160(ser))


def parse_uncompressed_pubkey(hex_str: str) -> Optional[Tuple[int, int]]:
    """Parse a 65-byte uncompressed SEC public key (04 || X || Y)."""
    h = (hex_str or "").strip()
    if not h.startswith("04") or len(h) != 130:
        return None
    try:
        pt = (int(h[2:66], 16), int(h[66:], 16))
    except ValueError:
        return None
    x, y = pt
    if (y * y - (x * x * x + B)) % P != 0:
        return None
    return pt


def parse_der_signature(der: bytes) -> Tuple[int, int]:
    """Parse a DER-encoded ECDSA signature as found in Bitcoin scriptSigs."""
    if not der or der[0] != 0x30:
        raise ValueError("not a DER SEQUENCE")
    i = 2
    if der[i] != 0x02:
        raise ValueError("expected INTEGER for r")
    rlen = der[i + 1]
    r = int.from_bytes(der[i + 2:i + 2 + rlen], "big")
    i += 2 + rlen
    if der[i] != 0x02:
        raise ValueError("expected INTEGER for s")
    slen = der[i + 1]
    s = int.from_bytes(der[i + 2:i + 2 + slen], "big")
    return r, s


def _varint(n: int) -> bytes:
    if n < 0xFD:
        return bytes([n])
    if n <= 0xFFFF:
        return b"\xfd" + n.to_bytes(2, "little")
    if n <= 0xFFFFFFFF:
        return b"\xfe" + n.to_bytes(4, "little")
    return b"\xff" + n.to_bytes(8, "little")


BITCOIN_MSG_MAGIC = b"\x18Bitcoin Signed Message:\n"


def message_hash(message: str) -> bytes:
    """The digest a Bitcoin 'signed message' commits to."""
    msg = message.encode("utf-8")
    return hash256(BITCOIN_MSG_MAGIC + _varint(len(msg)) + msg)


def ecdsa_verify(pub: Tuple[int, int], digest: bytes, r: int, s: int) -> bool:
    if not (0 < r < N and 0 < s < N):
        return False
    z = int.from_bytes(digest, "big")
    w = _inv(s, N)
    p1 = point_mul(z * w % N, G)
    p2 = point_mul(r * w % N, pub)
    pt = point_add(p1, p2)
    return pt is not None and pt[0] % N == r


def recover_pubkey(digest: bytes, r: int, s: int, rec_id: int) -> Optional[Tuple[int, int]]:
    """Public-key recovery, as used by Bitcoin's compact signature format."""
    if not (0 < r < N and 0 < s < N) or not 0 <= rec_id < 4:
        return None
    x = r + (N if rec_id >= 2 else 0)
    if x >= P:
        return None
    pt = _decompress(x, bool(rec_id & 1))
    if pt is None or point_mul(N, pt) is not None:
        return None
    z = int.from_bytes(digest, "big")
    rinv = _inv(r, N)
    q = point_add(point_mul((s * rinv) % N, pt),
                  point_mul((-z * rinv) % N, G))
    return q


@dataclass
class SignedMessageResult:
    address_claimed: Optional[str]
    address_recovered: Optional[str]
    valid: bool
    r: Optional[int] = None
    s: Optional[int] = None
    compressed: Optional[bool] = None
    error: str = ""
    notes: List[str] = field(default_factory=list)


def verify_signed_message(message: str, signature_b64: str,
                          address: Optional[str] = None) -> SignedMessageResult:
    """Verify a Bitcoin-style signed message (the format wallets expose as
    'Sign Message'). Recovers the signing address and compares it to ``address``.

    A pass proves control of the private key for the recovered address AT SIGNING
    TIME. It does not prove who that person is, and it does not prove the key is
    historically significant - that is an attribution question, not a crypto one.
    """
    import base64
    try:
        raw = base64.b64decode(signature_b64, validate=False)
    except Exception as exc:
        return SignedMessageResult(address, None, False, error="bad base64: %s" % exc)
    if len(raw) != 65:
        return SignedMessageResult(address, None, False,
                                   error="expected 65-byte compact signature, got %d"
                                         % len(raw))
    header = raw[0]
    if not 27 <= header <= 34:
        return SignedMessageResult(address, None, False,
                                   error="header byte %d out of range" % header)
    compressed = header >= 31
    rec_id = (header - 27) & 3
    r = int.from_bytes(raw[1:33], "big")
    s = int.from_bytes(raw[33:65], "big")
    digest = message_hash(message)
    pub = recover_pubkey(digest, r, s, rec_id)
    if pub is None:
        return SignedMessageResult(address, None, False, r=r, s=s,
                                   compressed=compressed,
                                   error="public key recovery failed")
    recovered = pubkey_to_address(pub, compressed)
    ok = ecdsa_verify(pub, digest, r, s) and (address is None or recovered == address)
    res = SignedMessageResult(address, recovered, ok, r=r, s=s, compressed=compressed)
    if address is not None and recovered != address:
        res.notes.append("Recovered address does not match the claimed address. "
                         "The signature is valid for a DIFFERENT key.")
    res.notes.append("A valid signature proves key control only. It carries no "
                     "evidence about the identity or historical role of the signer.")
    return res


@dataclass
class ECDSANonceFindings:
    signature_count: int
    distinct_r: int
    repeated_r: List[Tuple[str, str, int]] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)


def find_ecdsa_nonce_reuse(sigs: List[Dict]) -> ECDSANonceFindings:
    """Detect repeated ECDSA nonces across a corpus of (r, s, digest, label) dicts.

    Nonce reuse is the one ECDSA failure that is detectable from purely public data,
    because r = (kG).x depends only on k. It has really happened on Bitcoin mainnet
    (notably the 2013 Android SecureRandom failures), so this is a live check rather
    than a theoretical one.
    """
    by_r: Dict[int, List[Dict]] = {}
    for sig in sigs:
        by_r.setdefault(sig["r"], []).append(sig)
    f = ECDSANonceFindings(signature_count=len(sigs), distinct_r=len(by_r))
    for r, group in by_r.items():
        if len(group) > 1:
            for i in range(len(group)):
                for j in range(i + 1, len(group)):
                    f.repeated_r.append((group[i].get("label", "?"),
                                         group[j].get("label", "?"), r))
    if not f.repeated_r:
        f.notes.append("No repeated ECDSA nonce in the supplied corpus.")
    else:
        f.notes.append("Repeated nonce detected: the private key for the affected "
                       "address is recoverable in closed form from public data.")
    return f


def recover_ecdsa_key(r: int, s1: int, z1: int, s2: int, z2: int) -> Optional[int]:
    """Recover an ECDSA private key from two signatures that shared a nonce."""
    ds = (s1 - s2) % N
    if ds == 0:
        return None
    k = ((z1 - z2) * _inv(ds, N)) % N
    return ((s1 * k - z1) * _inv(r, N)) % N
